tup=(12,63,45,72,25,12,45,72,25)
print("Type of tuple :",type(tup))
print("Print the count tuples element :",tup.count(12))
print("Print the index of tuples element :",tup.index(72))
print("Print the length of tuples element :",len(tup))
print("Print the max of tuples element :",max(tup))
print("Print the min of tuples element :",min(tup))
print("Print the sum of tuples element :",sum(tup))
print("Print the sorted of tuples element :",sorted(tup))
print("Print the sorted of tuples element in reverse order :",sorted(tup,reverse=True))