str="i am a coder"
print("Print The String :",str)
print("Print The String in Upper case :",str.upper())
print("Print The String in Lower case :",str.lower())
print("Return if string substr True/False :",str.endswith("der"))
print("Capitalized 1st character :",str.capitalize())
print("Count the occurrence of substr :",str.count("a"))
print("Return index each character :",str.find("c"))
print("Replace character string :",str.replace("a","A"))
print("Every word capitalized :",str.title())
print("Index of string :",str.index("r"))
print("Return alphabet only :",str.isalpha())
print("Return digit only :",str.isdigit())
print("Return alphanumeric only :",str.isalnum())