list=[44,13,80,42,95,27,39,13,24,17,13,16,10,53,13]
print("Print the list :",list)
list.reverse()
print("Reverse order of list:",list)
list.sort()
print("Sorted order of list:",list)
list.sort(reverse=True)
print("Sorted order of list in reverse:",list)
list.append(8)
print("Append the list :",list)
list.remove(44)
print("Remove the list :",list)
list.pop(2)
print("Pop the list :",list)
print("Maximum number of list :",max(list))
print("Minimum number of list :",min(list))
print("Count of number of list :",list.count(13))
print("Sum of list :",sum(list))
print("Length of list :",len(list))